### ISSUE TITLE
Any plans for 0.17 Update?

### ISSUE THREAD

**Issue by Xearoxde** [lingo/advanced-logistics-system#1]
Do you have any plans to upgrade the mod for version 0.17?

**Comment by lingo** [comment]
I've released an initial upgrade for 0.17.x.



https://github.com/lingo/advanced-logistics-system



This probably needs more testing!



Cheers,

- Lucas





---- On Mon, 18 Mar 2019 09:38:39 +1300 Xearoxde <notifications@github.com> wrote ----



Do you have any plans to upgrade the mod for version 0.17?

**Comment by Horse4Horse** [comment]
Hi, nice work, dude. But only latest version? Because mod doesn't work with 0.16.51, you have no previous versions, like 0.6.0? Thanks!

**Comment by lingo** [comment]
The previous version 0.6.1 (not properly tagged, I'll fix that) works for 0.16.8, I believe. What's failing on 0.16.51?

**Comment by Horse4Horse** [comment]
In releases I didn't find 0.6.0 nor 0.6.1, latest is 0.5.1 and requires 0.15 game version. Maybe I missed something?

**Comment by Horse4Horse** [comment]
Ah, I found a way to download from commits. Sorry my bad, just still getting lost on github :D
Thanks for the updates man!

**Comment by Xearoxde** [comment]
> The previous version 0.6.1 (not properly tagged, I'll fix that) works for 0.16.8, I believe. What's failing on 0.16.51?

Thank You lingo! The version works perfectly with the current version of Factorio!

**Comment by TheKoopa321** [comment]
It doesn't work anymore since an update a few days ago.
I proposed a change (or maybe not, I never used github) but basically if you replace lsplayer = table.deepcopy(data.raw.player.player)  with lsplayer = table.deepcopy(data.raw.character.character) in controller.lua it should work fine.

**Comment by lingo** [comment]
I'll update this ASAP, thanks
